[icons]
# font awesome
TelegramDesktop = "ï‹†"
telegram-desktop_telegram-desktop = "ï‹†"
Firefox = "ï‰©"
Alacritty = "ï„ "
Thunderbird = "ïƒ "
# smile emoji
MyNiceProgram = "ğŸ˜›"
KeeWeb = 'ï‚„'
"org.gnome.Nautilus" = 'ï»'
Evince = 'ï‡'

[aliases]
TelegramDesktop = "Telegram"
telegram-desktop_telegram-desktop = "Telegram"
"org.gnome.Nautilus" = "Nautilus"
