[icons]
# font awesome
TelegramDesktop = "ï‹†"
telegram-desktop_telegram-desktop = "ï‹†"
Telegram = "ï‹†"
Firefox = "ï‰©"
Chromium = "ï‰©"
Alacritty = "ï„ "
HostTerminal = "ï„ "
Thunderbird = "ïƒ "
# smile emoji
MyNiceProgram = "ğŸ˜›"
KeeWeb = 'ï‚„'
"org.gnome.Nautilus" = 'ï»'
Evince = 'ï‡'

[aliases]
TelegramDesktop = "Telegram"
"org.telegram.desktop" = "Telegram"
telegram-desktop_telegram-desktop = "Telegram"
firefox = "Firefox"
thunderbird = "Thunderbird"
"org.gnome.Nautilus" = "Nautilus"
chrome-aicfnmoekkcocaklikapnhacomcehkae-Default = "Slack"
gnome-terminal-server = "HostTerminal"

[options]
remove-duplicates = true
